apiVersion: v1
kind: Service
metadata:
  name: telecom-frontend
spec:
  type: LoadBalancer
  selector:
    app: telecom-frontend
  ports:
    - port: 3000
      targetPort: 80
      protocol: TCP
      name: http
